#' Clean point locations dataframe.
#'
#' \code{clean_points} cleans and checks the dataframe of point locations
#'  generated by \code{load_gdb_points}.
#'
#'  @param data Dataframe. Point locations object to be cleaned.
#'  @return Data frame with three columns: point.id, x.coord,
#'    and y.coord. Returns complete rows only.
clean_locs <- function(data=NULL){
  colnames(data)[1] <- "point.id"
  colnames(data)[2] <- "x"
  colnames(data)[3] <- "y"
  data$x <- round(data$x, 1)
  data$y <- round(data$y, 1)
#   if (sum(duplicated(data))!=0){
#     data <- data[!duplicated(data), ]
#     warning("Duplicate points removed from data!")
#   }
#   if (sum(duplicated(data$point.id))!=0){
#     warning("Points in data with same ID at different locations!")
#   }
#   if (sum(duplicated(data[ , 2:3]))!=0){
#     warning("Points in data with different IDs at same location!")
#   }
  data
}

#' Clean LAI dataframe.
#'
#' \code{clean_lai} cleans and checks a dataframe of lai values in the
#'  format as generated by \code{load_dbfs}.
#'
#'  @param data Dataframe. Dataframe of LAI values to be cleaned.
#'  @return Data frame with a point.id column and one column for each available
#'    LAI reading.
clean_lai <- function(data=NULL){
  colnames(data)[1] <- "point.id"
  colnames(data) <- tolower(colnames(data))
#   if (sum(duplicated(data))!=0){
#     data <- data[!duplicated(data), ]
#     warning("Duplicate points removed from data!")
#   }
#   if (sum(duplicated(data$point.id))!=0){
#     warning("Points in data with same ID and different LAI readings!")
#   }
  data[data==-9999] <- NA
  data
}

#' Melt LAI dataframe.
#'
#' \code{melt_lai} melts a wide dataframe of LAI values as generated by
#'  \code{load_dbfs} and and \code{clean_lai} into a melted data set. Cleans
#'  date values into proper format.
#'
#'  @param data Dataframe. Wide dataframe of LAI values.
#'  @return Data frame with a point.id column, a column for the date,
#'    and a column for the LAI value on the associated date.
melt_lai <- function(data=NULL){
  temp <- reshape2::melt(data, id.vars="point.id", variable.name="date", value.name="lai")
  temp$date <- as.Date(substring(temp$date, 2), "%Y%m%d")
  temp
}

